version: '3.8'

services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap_container
    environment:
      - LDAP_ORGANISATION=Test
      - LDAP_DOMAIN=test.local
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin_container
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "8888:80"
    depends_on:
      - openldap

volumes:
  ldap_data:
  ldap_config:
