services:
  openldap-selenium:
    extends:
      file: ./compose-services.yml
      service: openldap
    environment:
      - LDAP_ORGANISATION=Test
      - LDAP_DOMAIN=test.local
      - LDAP_ADMIN_PASSWORD=admin
    networks:
      - net-selenium
    volumes:
      - ldap-data-selenium:/var/lib/ldap
      - ldap-config-selenium:/etc/ldap/slapd.d

  api-build-selenium:
    extends:
      file: ./compose-services.yml
      service: api-build
    networks:
      - net-selenium
    volumes:
      - api-app-selenium:/app

  api-selenium:
    extends:
      file: ./compose-services.yml
      service: api
    depends_on:
      openldap-selenium:
        condition: service_started
      api-build-selenium:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LDAP_ADDRESS: openldap-selenium
      LDAP_PORT: 389
      LDAP_DOMAIN: test.local
      LDAP_USERNAME: admin
      LDAP_PASSWORD: admin
      DEFAULT_ADMIN_NAME: admin
      DEFAULT_ADMIN_PASSWORD: adminpass
    networks:
      net-selenium:
        aliases:
          - api
    volumes:
      - api-app-selenium:/app:ro

  webapp-build-selenium:
    extends:
      file: ./compose-services.yml
      service: webapp-build
    networks:
      - net-selenium
    volumes:
      - webapp-app-selenium:/app

  nginx-selenium:
    extends:
      file: ./compose-services.yml
      service: nginx
    depends_on:
      api-build-selenium:
        condition: service_completed_successfully
      webapp-build-selenium:
        condition: service_completed_successfully
    networks:
      - net-selenium
    ports:
      - 8080:80
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - webapp-app-selenium:/app:ro

  selenium-tests:
    build:
      context: ..
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/sdk:7.0
        COPY ./NeuLdapMgnt/WebApp.Tests /app/WebApp.Tests
        COPY ./NeuLdapMgnt/Models /app/Models
        WORKDIR /app/WebApp.Tests
        ENTRYPOINT [ "dotnet", "test", "--logger", "liquid.md;logfilename=/app/WebApp.Tests/README.md" ]
    environment:
      DEFAULT_ADMIN_NAME: admin
      DEFAULT_ADMIN_PASSWORD: adminpass
      DEFAULT_MANAGEMENT_URL: http://nginx-selenium:80
      DEFAULT_SELENIUM_HUB_URL: http://selenium-hub:4444
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      selenium-hub:
        condition: service_started
      selenium-node-firefox:
        condition: service_started
      nginx-selenium:
        condition: service_started
    volumes:
      - ../NeuLdapMgnt/WebApp.Tests:/app/WebApp.Tests
    networks:
      - net-selenium

  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      - net-selenium

  selenium-node-firefox:
    image: selenium/node-firefox:4.17.0-20240123
    shm_size: 2gb
    depends_on:
      selenium-hub:
        condition: service_started
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - net-selenium

networks:
  net-selenium:

volumes:
  ldap-data-selenium:
  ldap-config-selenium:
  api-app-selenium:
  webapp-app-selenium:
