name: neu-ldap-mgnt-api-tests

services:
  openldap:
    extends:
      file: ./compose-services.yml
      service: openldap

  api-build:
    extends:
      file: ./compose-services.yml
      service: api-build
    volumes:
      - api-app:/app

  api:
    extends:
      file: ./compose-services.yml
      service: api
    depends_on:
      api-build:
        condition: service_completed_successfully
      openldap:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LDAP_ADDRESS: openldap
      LOGS_DIR: /logs
    volumes:
      - api-app:/app:ro

  tests:
    extends:
      file: ./compose-services.yml
      service: api-tests
    depends_on:
      - api
    environment:
      API_URL: http://api:5000
      LDAP_ADDRESS: openldap
      LDAP_PORT: 389
      LDAP_DOMAIN: neu.local
      LDAP_USERNAME: admin
      LDAP_PASSWORD: admin
    volumes:
      - ../testing/results:/tr

volumes:
  api-app:
