services:
  api-test-openldap:
    extends:
      file: ./compose-services.yml
      service: openldap
    networks:
      - api-test-net

  api-test-api-build:
    extends:
      file: ./compose-services.yml
      service: api-build
    networks:
      - api-test-net
    volumes:
      - api-test-api-app:/app

  api-test-api:
    extends:
      file: ./compose-services.yml
      service: api
    depends_on:
      api-test-api-build:
        condition: service_completed_successfully
      api-test-openldap:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LDAP_ADDRESS: api-test-openldap
      LOGS_DIR: /logs
    networks:
      api-test-net:
        aliases:
          - api
    volumes:
      - api-test-api-app:/app:ro

  api-test-tests:
    extends:
      file: ./compose-services.yml
      service: api-tests
    depends_on:
      - api-test-api
    environment:
      API_URL: http://api:5000
      LDAP_ADDRESS: api-test-openldap
      LDAP_PORT: 389
      LDAP_DOMAIN: neu.local
      LDAP_USERNAME: admin
      LDAP_PASSWORD: admin
    networks:
      - api-test-net
    volumes:
      - ../docs/test-results:/tr

networks:
  api-test-net:


volumes:
  api-test-api-app:
