name: neu-ldap-mgnt-selenium-tests

services:
  openldap:
    extends:
      file: ./compose-services.yml
      service: openldap
    environment:
      - LDAP_ORGANISATION=Test
      - LDAP_DOMAIN=test.local
      - LDAP_ADMIN_PASSWORD=admin
    volumes:
      - ldap-data-selenium:/var/lib/ldap
      - ldap-config-selenium:/etc/ldap/slapd.d

  api-build:
    extends:
      file: ./compose-services.yml
      service: api-build
    volumes:
      - api-app-selenium:/app

  api:
    extends:
      file: ./compose-services.yml
      service: api
    depends_on:
      openldap:
        condition: service_started
      api-build:
        condition: service_completed_successfully
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LDAP_ADDRESS: openldap
      LDAP_PORT: 389
      LDAP_DOMAIN: test.local
      LDAP_USERNAME: admin
      LDAP_PASSWORD: admin
      DEFAULT_ADMIN_NAME: admin
      DEFAULT_ADMIN_PASSWORD: adminpass
    volumes:
      - api-app-selenium:/app:ro

  webapp-build:
    extends:
      file: ./compose-services.yml
      service: webapp-build
    volumes:
      - webapp-app-selenium:/app

  nginx:
    extends:
      file: ./compose-services.yml
      service: nginx
    depends_on:
      api-build:
        condition: service_completed_successfully
      webapp-build:
        condition: service_completed_successfully
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - webapp-app-selenium:/app:ro

  tests:
    build:
      context: ..
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/sdk:7.0
        COPY ./NeuLdapMgnt/WebApp.Tests /app/WebApp.Tests
        COPY ./NeuLdapMgnt/Models /app/Models
        WORKDIR /app/WebApp.Tests
        ENTRYPOINT [ "dotnet", "test", "--logger", "trx;LogFileName=/tr/selenium.trx" ]
    environment:
      DEFAULT_ADMIN_NAME: admin
      DEFAULT_ADMIN_PASSWORD: adminpass
      ASPNETCORE_ENVIRONMENT: Docker
      SELENIUM_HUB_URL: http://hub:4444
      WEBAPP_URL: http://nginx:80
    depends_on:
      hub:
        condition: service_started
      node-firefox:
        condition: service_started
      nginx:
        condition: service_started
    volumes:
      - ../test-results:/tr

  hub:
    image: selenium/hub:4.0.0
    container_name: hub

  node-firefox:
    image: selenium/node-firefox:4.17.0-20240123
    shm_size: 2gb
    depends_on:
      hub:
        condition: service_started
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

volumes:
  ldap-data-selenium:
  ldap-config-selenium:
  api-app-selenium:
  webapp-app-selenium:
