name: neu-ldap-mgnt-demo

services:
  postgres:
    extends:
      file: ./compose-services.yml
      service: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  openldap:
    extends:
      file: ./compose-services.yml
      service: openldap
    ports:
      - 389:389
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  ldapadmin:
    extends:
      file: ./compose-services.yml
      service: ldapadmin
    depends_on:
      - openldap
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - 8888:80

  api-build:
    extends:
      file: ./compose-services.yml
      service: api-build
    volumes:
      - api-app:/app

  api:
    extends:
      file: ./compose-services.yml
      service: api
    depends_on:
      api-build:
        condition: service_completed_successfully
      openldap:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      LDAP_ADDRESS: openldap
      POSTGRES_HOST: postgres
      LOG_TO_DB: true
      LOGS_DIR: /logs
      SECURITY_KEY: ITN3pnH472FGG71aC1AWFDrTn2TpgHtBuZdD/LYkD4bXe4hhAKWj8CsTfGPQJHr3qoY8/KM0zShbyreW6RapyGAL2M8JBOWLknXoC/1zJ4+9QOC7hpk4jqM13vHoJeL8JTKdYGCzx6gwZK9a4vgcsVCCc1QT6//WO7x0xdcZUsiHqp2t9PJjzLfMvK2nlaWe+aoBBPvsM4CAyWTMT8sZVHSmrjTunhVOn9cqoouHwe33a5grSf9Z9AhFtBTSH2DvlW4/DdA1kKcNeju/wZGhnE0DKNsguV6b5NcYLsRgU1NK2nrWd8yhUskOQCoDvLwnWc3Qto5l/AFnht08FSjLSQ==
    ports:
      - 5000:5000
    volumes:
      - api-app:/app:ro

  webapp-build:
    extends:
      file: ./compose-services.yml
      service: webapp-build
    volumes:
      - webapp-app:/app

  nginx:
    extends:
      file: ./compose-services.yml
      service: nginx
    depends_on:
      api-build:
        condition: service_completed_successfully
      webapp-build:
        condition: service_completed_successfully
      api:
        condition: service_started
    ports:
      - 8080:80
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - webapp-app:/app:ro

volumes:
  ldap-data:
  ldap-config:
  postgres-data:
  api-app:
  webapp-app:
