name: neu-ldap-mgnt-model-tests

services:
  tests:
    build:
      context: ..
      dockerfile_inline: |
        FROM mcr.microsoft.com/dotnet/sdk:7.0
        COPY ./NeuLdapMgnt/Models.Tests /app/Models.Tests
        COPY ./NeuLdapMgnt/Models /app/Models
        WORKDIR /app/Models.Tests
        ENTRYPOINT [ "dotnet", "test", "--logger", "trx;LogFileName=/tr/models.trx" ]
    volumes:
      - ../test-results:/tr
