name: Tests

on:
  push:
    branches: [ main ]
    paths: [ .github/workflows/run-tests.yml, NeuLdapMgnt/** ]
  pull_request:
    branches: [ main ]
    paths: [ .github/workflows/run-tests.yml, NeuLdapMgnt/** ]

permissions:
  checks: write
  pull-requests: write

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create test results directory
      run: mkdir test-results

    - name: Run Model tests
      run: make model-tests
      continue-on-error: true

    - name: Run API tests
      run: make api-tests
      continue-on-error: true

    - name: Run WebApp tests
      run: make web-tests
      continue-on-error: true

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results/*
        comment_on_pr: false
        check_run: true
